"""Create initial tables

Revision ID: 652aed9cfae6
Revises: 69fa4e5b63b6
Create Date: 2024-08-02 00:12:18.091594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652aed9cfae6'
down_revision: Union[str, None] = '69fa4e5b63b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_urls_original_url'), 'urls', ['original_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_original_url'), table_name='urls')
    # ### end Alembic commands ###
